### ISSUE TITLE
Implement Open311 in backend

### ISSUE THREAD

**Issue by VitalyIvanov** [Aalto-University-Hep7agon/city-feedback-hub-ui#12]
As a developer I want to work with Open311 service through our own backend to be ready to add additional features to it.

Only required for current issues API should be implemented.

Related tasks:
Aalto-University-Hep7agon/city-feedback-hub-backend#1
Aalto-University-Hep7agon/city-feedback-hub-backend#2
Aalto-University-Hep7agon/city-feedback-hub-tests#1

**Comment by tmhallik** [comment]
# Bug reports:

## Filtering multiple alternative parameters with a comma filters everything:
https://cityfeedbackhub-api.herokuapp.com/api/v1/requests.json?service_code=171,180
RETURNS                []
SHOULD RETURN   [a lot of feedback items with service_code 171 OR 180]

* +Appending a request resulting in a non-empty response, with a comma e.g. "https://cityfeedbackhub-api.herokuapp.com/api/v1/requests.json?service_code=180" returns an empty list.*

## Empty params for numeric params filter everything:
https://cityfeedbackhub-api.herokuapp.com/api/v1/requests.json?service_request_id OR https://cityfeedbackhub-api.herokuapp.com/api/v1/requests.json?service_code=
RETURNS                 []
SHOULD RETURN    [a full list of items]

* +"https://cityfeedbackhub-api.herokuapp.com/api/v1/requests.json?agency_responsible" [uses a non-numeric param] returns a proper full list.*
