### ISSUE TITLE
Enable geolocation feature in UI

### ISSUE THREAD

**Issue by VitalyIvanov** [Aalto-University-Hep7agon/city-feedback-hub-ui#15]

**Comment by obscurage** [comment]
This feature is now availble in the UI. However, no other functionality than printing the location to console is implemented. What else can be done to this before getting the location and radius filtering online?
@VitalyIvanov

**Comment by obscurage** [comment]
The mentioned features have been implemented to backend.
Now uses a hard-coded value of 3000 (meters) for radius.

The feature has been implemented!
