### ISSUE TITLE
See the list of feedbacks filtered by different criteria

### ISSUE THREAD

**Issue by mehukatti212** [Aalto-University-Hep7agon/city-feedback-hub-ui#2]
As a user I want to see the list of feedbacks filtered by different criteria to find feedbacks that interest me.

E.g.
- open or closed feedback
- based agency responsible
- date (e.g. from calendar: start and end date)
- aspa status notes (in progress, fixed, etc.)
- owner_name
- etc.

Related tasks:
#18 
#19 
#20 
#32 
Aalto-University-Hep7agon/city-feedback-hub-tests#2

Acceptance criteria:

**Comment by madaian** [comment]
![image](https://cloud.githubusercontent.com/assets/11146256/11470687/7147cacc-9768-11e5-9492-b9e98c7c47f9.png)
![image](https://cloud.githubusercontent.com/assets/11146256/11470691/75322448-9768-11e5-85aa-ec34c33fb332.png)
Possible filtering method / UI view. Clicking the search button should update the list of visible feedback.

**Comment by obscurage** [comment]
The prototype now has criteria for status and location.
Feedbacks can be filtered with word search.
Further criteria etc. will be implemented later on.
