### ISSUE TITLE
Create mockups of UI combining all features

### ISSUE THREAD

**Issue by madaian** [Aalto-University-Hep7agon/city-feedback-hub-ui#23]

**Comment by madaian** [comment]
First mockup using balsamiq; most likely not mobile-friendly:

![all feedback sketch](https://cloud.githubusercontent.com/assets/11146256/11219924/e01a74fc-8d65-11e5-842f-2b59a029f70f.png)
![feedback around me 01](https://cloud.githubusercontent.com/assets/11146256/11219925/e01f1e26-8d65-11e5-968c-9ad0583af307.png)
![feedback around me 02](https://cloud.githubusercontent.com/assets/11146256/11219927/e034ab7e-8d65-11e5-84d2-05ea79494e7c.png)
![search 01 sketch](https://cloud.githubusercontent.com/assets/11146256/11219926/e02f36e4-8d65-11e5-941a-bcee3fe12e5b.png)
![search 02 sketch](https://cloud.githubusercontent.com/assets/11146256/11219928/e036bb08-8d65-11e5-934d-01a06941892a.png)

**Comment by mehukatti212** [comment]
Hi,

remember: "UI would be designed for mobile first". Don't throw the mockups away, i think this is an excellent start. There is only week before the sprint 1 closes and the first review session with aalto. Can u come up with a mobile mock up before the dl?

peter

**Comment by madaian** [comment]
![image](https://cloud.githubusercontent.com/assets/11146256/11469911/616ddfe8-9762-11e5-9773-1acca19f5a48.png)
![image](https://cloud.githubusercontent.com/assets/11146256/11469917/65c96eae-9762-11e5-9687-5ffa37bb44c5.png)
Not mobile-friendly, still unfinished mockups

**Comment by madaian** [comment]
![image](https://cloud.githubusercontent.com/assets/11146256/11469974/d0208008-9762-11e5-8398-28fe195a87d1.png)
Previous design fitted for mobile; still not user friendly

**Comment by madaian** [comment]
![image](https://cloud.githubusercontent.com/assets/11146256/11563913/0d14ef20-99df-11e5-805d-ef30e316f663.png)
The latest mockup. More comments and details [here](https://cityfeedbackhub.mybalsamiq.com/projects/uidesign/Main) - you can even try out what happens when you click the 'more options' and 'piilota kartta' links!

**Comment by obscurage** [comment]
Suppose this task is done! If not, let me know! @madaian 

I'll close this for now!
