### ISSUE TITLE
Create a simple prototype based on React.js tutorial

### ISSUE THREAD

**Issue by obscurage** [Aalto-University-Hep7agon/city-feedback-hub-ui#27]
Using sample data from Open311
Modifying the tutorial to meet our needs

**Comment by sevesalm** [comment]
We have to make sure there are no licencing or copyright issues if we use the tutorial code. Or rewrite if needed.

I made some refactorings today. To simplify things.

**Comment by obscurage** [comment]
The current application has been built on top of the tutorial, so this can be deemed done. However, specs of the proto weren't that detailed and should be reviewed.

**Comment by obscurage** [comment]
Done!
