### ISSUE TITLE
Add navbar to front-end

### ISSUE THREAD

**Issue by obscurage** [Aalto-University-Hep7agon/city-feedback-hub-ui#35]
Contains 
- site logo
- links to other pages
- ...

**Comment by madaian** [comment]
![image](https://cloud.githubusercontent.com/assets/11146256/11469586/12a43846-9760-11e5-87a6-0910f9626d80.png)
Navbar mockup

**Comment by obscurage** [comment]
Navbar added to UI. Will be enhanced later with advanced filtering.
